# -*- coding: utf-8 -*-
"""part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ILX51RnaY5j9csnZfHAcQQltbe9Mnkd
"""

def say_hello_three_times():
  for _ in range(2):
    print('Hello beautifu people, its very hot today!')

say_hello_three_times()

def say_hello_multiple_times(n):
  print(f'saying hello {n} times')
  for _ in range(n):
      print('Hello beautiful people, its very hot today!')
      print()

say_hello_multiple_times(2)
say_hello_multiple_times(0)